services:
  laravel:
    build:
      context: .
      args:
        UID: 1000 # Remplacez par votre UID réel
        GID: 1000 # Remplacez par votre GID réel
    volumes:
      - ./:/app
    ports:
      - '8002:8000'
      - '5173:5173' # Port hôte 5173, conteneur 5173 (ajouté)
    working_dir: /app
    tty: true

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - '3308:3306'
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  dbdata:
